///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class SoilTestingTypeListModelDATA2 {
/*
{
  "TABLE2": 1
} 
*/

  String? TABLE2;

  SoilTestingTypeListModelDATA2({
    this.TABLE2,
  });
  SoilTestingTypeListModelDATA2.fromJson(Map<String, dynamic> json) {
    TABLE2 = json['TABLE2']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['TABLE2'] = TABLE2;
    return data;
  }
}

class SoilTestingTypeListModelDATA1 {
/*
{
  "TABLE1": 1
} 
*/

  String? TABLE1;

  SoilTestingTypeListModelDATA1({
    this.TABLE1,
  });
  SoilTestingTypeListModelDATA1.fromJson(Map<String, dynamic> json) {
    TABLE1 = json['TABLE1']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['TABLE1'] = TABLE1;
    return data;
  }
}

class SoilTestingTypeListModelDATA {
/*
{
  "TESTING_TYPE_ID": 1,
  "TESTING_TYPE_NAME": "Soil Analysis",
  "AMOUNT": 950,
  "VIDEO_URL": "RE00M9NANoc",
  "TESTING_IMG": "https://myadmin.cropguru.in//images/images88886687726913452023.jpeg",
  "STATUS": "Active",
  "REG_DATE": "14 Mar 2022"
} 
*/

  String? TESTING_TYPE_ID;
  String? TESTING_TYPE_NAME;
  String? AMOUNT;
  String? VIDEO_URL;
  String? TESTING_IMG;
  String? STATUS;
  String? REG_DATE;

  SoilTestingTypeListModelDATA({
    this.TESTING_TYPE_ID,
    this.TESTING_TYPE_NAME,
    this.AMOUNT,
    this.VIDEO_URL,
    this.TESTING_IMG,
    this.STATUS,
    this.REG_DATE,
  });
  SoilTestingTypeListModelDATA.fromJson(Map<String, dynamic> json) {
    TESTING_TYPE_ID = json['TESTING_TYPE_ID']?.toString();
    TESTING_TYPE_NAME = json['TESTING_TYPE_NAME']?.toString();
    AMOUNT = json['AMOUNT']?.toString();
    VIDEO_URL = json['VIDEO_URL']?.toString();
    TESTING_IMG = json['TESTING_IMG']?.toString();
    STATUS = json['STATUS']?.toString();
    REG_DATE = json['REG_DATE']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['TESTING_TYPE_ID'] = TESTING_TYPE_ID;
    data['TESTING_TYPE_NAME'] = TESTING_TYPE_NAME;
    data['AMOUNT'] = AMOUNT;
    data['VIDEO_URL'] = VIDEO_URL;
    data['TESTING_IMG'] = TESTING_IMG;
    data['STATUS'] = STATUS;
    data['REG_DATE'] = REG_DATE;
    return data;
  }
}

class SoilTestingTypeListModel {
/*
{
  "ResponseCode": "0",
  "ResponseMessage": "Get_TestingTypeList List",
  "ID": null,
  "DATA": [
    {
      "TESTING_TYPE_ID": 1,
      "TESTING_TYPE_NAME": "Soil Analysis",
      "AMOUNT": 950,
      "VIDEO_URL": "RE00M9NANoc",
      "TESTING_IMG": "https://myadmin.cropguru.in//images/images88886687726913452023.jpeg",
      "STATUS": "Active",
      "REG_DATE": "14 Mar 2022"
    }
  ],
  "DATA1": [
    {
      "TABLE1": 1
    }
  ],
  "DATA2": [
    {
      "TABLE2": 1
    }
  ]
} 
*/

  String? ResponseCode;
  String? ResponseMessage;
  String? ID;
  List<SoilTestingTypeListModelDATA?>? DATA;
  List<SoilTestingTypeListModelDATA1?>? DATA1;
  List<SoilTestingTypeListModelDATA2?>? DATA2;

  SoilTestingTypeListModel({
    this.ResponseCode,
    this.ResponseMessage,
    this.ID,
    this.DATA,
    this.DATA1,
    this.DATA2,
  });
  SoilTestingTypeListModel.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseMessage = json['ResponseMessage']?.toString();
    ID = json['ID']?.toString();
  if (json['DATA'] != null) {
  final v = json['DATA'];
  final arr0 = <SoilTestingTypeListModelDATA>[];
  v.forEach((v) {
  arr0.add(SoilTestingTypeListModelDATA.fromJson(v));
  });
    DATA = arr0;
    }
  if (json['DATA1'] != null) {
  final v = json['DATA1'];
  final arr0 = <SoilTestingTypeListModelDATA1>[];
  v.forEach((v) {
  arr0.add(SoilTestingTypeListModelDATA1.fromJson(v));
  });
    DATA1 = arr0;
    }
  if (json['DATA2'] != null) {
  final v = json['DATA2'];
  final arr0 = <SoilTestingTypeListModelDATA2>[];
  v.forEach((v) {
  arr0.add(SoilTestingTypeListModelDATA2.fromJson(v));
  });
    DATA2 = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseMessage'] = ResponseMessage;
    data['ID'] = ID;
    if (DATA != null) {
      final v = DATA;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA'] = arr0;
    }
    if (DATA1 != null) {
      final v = DATA1;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA1'] = arr0;
    }
    if (DATA2 != null) {
      final v = DATA2;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA2'] = arr0;
    }
    return data;
  }
}
