///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class WatherModelForecastForecastdayHourCondition {
/*
{
  "text": "Partly cloudy",
  "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
  "code": 1003
} 
*/

  String? text;
  String? icon;
  int? code;

  WatherModelForecastForecastdayHourCondition({
    this.text,
    this.icon,
    this.code,
  });
  WatherModelForecastForecastdayHourCondition.fromJson(Map<String, dynamic> json) {
    text = json['text']?.toString();
    icon = json['icon']?.toString();
    code = json['code']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['text'] = text;
    data['icon'] = icon;
    data['code'] = code;
    return data;
  }
}

class WatherModelForecastForecastdayHour {
/*
{
  "time_epoch": 1692642600,
  "time": "2023-08-22 00:00",
  "temp_c": 21.6,
  "temp_f": 70.9,
  "is_day": 0,
  "condition": {
    "text": "Partly cloudy",
    "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
    "code": 1003
  },
  "wind_mph": 4,
  "wind_kph": 6.5,
  "wind_degree": 191,
  "wind_dir": "SSW",
  "pressure_mb": 1008,
  "pressure_in": 29.77,
  "precip_mm": 0,
  "precip_in": 0,
  "humidity": 94,
  "cloud": 38,
  "feelslike_c": 21.6,
  "feelslike_f": 70.9,
  "windchill_c": 21.6,
  "windchill_f": 70.9,
  "heatindex_c": 24.4,
  "heatindex_f": 75.9,
  "dewpoint_c": 20.6,
  "dewpoint_f": 69.1,
  "will_it_rain": 0,
  "chance_of_rain": 0,
  "will_it_snow": 0,
  "chance_of_snow": 0,
  "vis_km": 10,
  "vis_miles": 6,
  "gust_mph": 7.8,
  "gust_kph": 12.6,
  "uv": 1
} 
*/

  int? time_epoch;
  String? time;
  double? temp_c;
  double? temp_f;
  int? is_day;
  WatherModelForecastForecastdayHourCondition? condition;
  int? wind_mph;
  double? wind_kph;
  int? wind_degree;
  String? wind_dir;
  int? pressure_mb;
  double? pressure_in;
  int? precip_mm;
  int? precip_in;
  int? humidity;
  int? cloud;
  double? feelslike_c;
  double? feelslike_f;
  double? windchill_c;
  double? windchill_f;
  double? heatindex_c;
  double? heatindex_f;
  double? dewpoint_c;
  double? dewpoint_f;
  int? will_it_rain;
  int? chance_of_rain;
  int? will_it_snow;
  int? chance_of_snow;
  int? vis_km;
  int? vis_miles;
  double? gust_mph;
  double? gust_kph;
  int? uv;

  WatherModelForecastForecastdayHour({
    this.time_epoch,
    this.time,
    this.temp_c,
    this.temp_f,
    this.is_day,
    this.condition,
    this.wind_mph,
    this.wind_kph,
    this.wind_degree,
    this.wind_dir,
    this.pressure_mb,
    this.pressure_in,
    this.precip_mm,
    this.precip_in,
    this.humidity,
    this.cloud,
    this.feelslike_c,
    this.feelslike_f,
    this.windchill_c,
    this.windchill_f,
    this.heatindex_c,
    this.heatindex_f,
    this.dewpoint_c,
    this.dewpoint_f,
    this.will_it_rain,
    this.chance_of_rain,
    this.will_it_snow,
    this.chance_of_snow,
    this.vis_km,
    this.vis_miles,
    this.gust_mph,
    this.gust_kph,
    this.uv,
  });
  WatherModelForecastForecastdayHour.fromJson(Map<String, dynamic> json) {
    time_epoch = json['time_epoch']?.toInt();
    time = json['time']?.toString();
    temp_c = json['temp_c']?.toDouble();
    temp_f = json['temp_f']?.toDouble();
    is_day = json['is_day']?.toInt();
    condition = (json['condition'] != null) ? WatherModelForecastForecastdayHourCondition.fromJson(json['condition']) : null;
    wind_mph = json['wind_mph']?.toInt();
    wind_kph = json['wind_kph']?.toDouble();
    wind_degree = json['wind_degree']?.toInt();
    wind_dir = json['wind_dir']?.toString();
    pressure_mb = json['pressure_mb']?.toInt();
    pressure_in = json['pressure_in']?.toDouble();
    precip_mm = json['precip_mm']?.toInt();
    precip_in = json['precip_in']?.toInt();
    humidity = json['humidity']?.toInt();
    cloud = json['cloud']?.toInt();
    feelslike_c = json['feelslike_c']?.toDouble();
    feelslike_f = json['feelslike_f']?.toDouble();
    windchill_c = json['windchill_c']?.toDouble();
    windchill_f = json['windchill_f']?.toDouble();
    heatindex_c = json['heatindex_c']?.toDouble();
    heatindex_f = json['heatindex_f']?.toDouble();
    dewpoint_c = json['dewpoint_c']?.toDouble();
    dewpoint_f = json['dewpoint_f']?.toDouble();
    will_it_rain = json['will_it_rain']?.toInt();
    chance_of_rain = json['chance_of_rain']?.toInt();
    will_it_snow = json['will_it_snow']?.toInt();
    chance_of_snow = json['chance_of_snow']?.toInt();
    vis_km = json['vis_km']?.toInt();
    vis_miles = json['vis_miles']?.toInt();
    gust_mph = json['gust_mph']?.toDouble();
    gust_kph = json['gust_kph']?.toDouble();
    uv = json['uv']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['time_epoch'] = time_epoch;
    data['time'] = time;
    data['temp_c'] = temp_c;
    data['temp_f'] = temp_f;
    data['is_day'] = is_day;
    if (condition != null) {
      data['condition'] = condition!.toJson();
    }
    data['wind_mph'] = wind_mph;
    data['wind_kph'] = wind_kph;
    data['wind_degree'] = wind_degree;
    data['wind_dir'] = wind_dir;
    data['pressure_mb'] = pressure_mb;
    data['pressure_in'] = pressure_in;
    data['precip_mm'] = precip_mm;
    data['precip_in'] = precip_in;
    data['humidity'] = humidity;
    data['cloud'] = cloud;
    data['feelslike_c'] = feelslike_c;
    data['feelslike_f'] = feelslike_f;
    data['windchill_c'] = windchill_c;
    data['windchill_f'] = windchill_f;
    data['heatindex_c'] = heatindex_c;
    data['heatindex_f'] = heatindex_f;
    data['dewpoint_c'] = dewpoint_c;
    data['dewpoint_f'] = dewpoint_f;
    data['will_it_rain'] = will_it_rain;
    data['chance_of_rain'] = chance_of_rain;
    data['will_it_snow'] = will_it_snow;
    data['chance_of_snow'] = chance_of_snow;
    data['vis_km'] = vis_km;
    data['vis_miles'] = vis_miles;
    data['gust_mph'] = gust_mph;
    data['gust_kph'] = gust_kph;
    data['uv'] = uv;
    return data;
  }
}

class WatherModelForecastForecastdayAstro {
/*
{
  "sunrise": "06:18 AM",
  "sunset": "07:01 PM",
  "moonrise": "10:59 AM",
  "moonset": "10:34 PM",
  "moon_phase": "Waxing Crescent",
  "moon_illumination": "26",
  "is_moon_up": 0,
  "is_sun_up": 0
} 
*/

  String? sunrise;
  String? sunset;
  String? moonrise;
  String? moonset;
  String? moon_phase;
  String? moon_illumination;
  int? is_moon_up;
  int? is_sun_up;

  WatherModelForecastForecastdayAstro({
    this.sunrise,
    this.sunset,
    this.moonrise,
    this.moonset,
    this.moon_phase,
    this.moon_illumination,
    this.is_moon_up,
    this.is_sun_up,
  });
  WatherModelForecastForecastdayAstro.fromJson(Map<String, dynamic> json) {
    sunrise = json['sunrise']?.toString();
    sunset = json['sunset']?.toString();
    moonrise = json['moonrise']?.toString();
    moonset = json['moonset']?.toString();
    moon_phase = json['moon_phase']?.toString();
    moon_illumination = json['moon_illumination']?.toString();
    is_moon_up = json['is_moon_up']?.toInt();
    is_sun_up = json['is_sun_up']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sunrise'] = sunrise;
    data['sunset'] = sunset;
    data['moonrise'] = moonrise;
    data['moonset'] = moonset;
    data['moon_phase'] = moon_phase;
    data['moon_illumination'] = moon_illumination;
    data['is_moon_up'] = is_moon_up;
    data['is_sun_up'] = is_sun_up;
    return data;
  }
}

class WatherModelForecastForecastdayDayCondition {
/*
{
  "text": "Moderate rain",
  "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
  "code": 1189
} 
*/

  String? text;
  String? icon;
  int? code;

  WatherModelForecastForecastdayDayCondition({
    this.text,
    this.icon,
    this.code,
  });
  WatherModelForecastForecastdayDayCondition.fromJson(Map<String, dynamic> json) {
    text = json['text']?.toString();
    icon = json['icon']?.toString();
    code = json['code']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['text'] = text;
    data['icon'] = icon;
    data['code'] = code;
    return data;
  }
}

class WatherModelForecastForecastdayDay {
/*
{
  "maxtemp_c": 26.1,
  "maxtemp_f": 79,
  "mintemp_c": 21.3,
  "mintemp_f": 70.3,
  "avgtemp_c": 23.4,
  "avgtemp_f": 74.2,
  "maxwind_mph": 13.4,
  "maxwind_kph": 21.6,
  "totalprecip_mm": 12.9,
  "totalprecip_in": 0.51,
  "totalsnow_cm": 0,
  "avgvis_km": 7.6,
  "avgvis_miles": 4,
  "avghumidity": 88,
  "daily_will_it_rain": 1,
  "daily_chance_of_rain": 96,
  "daily_will_it_snow": 0,
  "daily_chance_of_snow": 0,
  "condition": {
    "text": "Moderate rain",
    "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
    "code": 1189
  },
  "uv": 5
} 
*/

  double? maxtemp_c;
  int? maxtemp_f;
  double? mintemp_c;
  double? mintemp_f;
  double? avgtemp_c;
  double? avgtemp_f;
  double? maxwind_mph;
  double? maxwind_kph;
  double? totalprecip_mm;
  double? totalprecip_in;
  int? totalsnow_cm;
  double? avgvis_km;
  int? avgvis_miles;
  int? avghumidity;
  int? daily_will_it_rain;
  int? daily_chance_of_rain;
  int? daily_will_it_snow;
  int? daily_chance_of_snow;
  WatherModelForecastForecastdayDayCondition? condition;
  int? uv;

  WatherModelForecastForecastdayDay({
    this.maxtemp_c,
    this.maxtemp_f,
    this.mintemp_c,
    this.mintemp_f,
    this.avgtemp_c,
    this.avgtemp_f,
    this.maxwind_mph,
    this.maxwind_kph,
    this.totalprecip_mm,
    this.totalprecip_in,
    this.totalsnow_cm,
    this.avgvis_km,
    this.avgvis_miles,
    this.avghumidity,
    this.daily_will_it_rain,
    this.daily_chance_of_rain,
    this.daily_will_it_snow,
    this.daily_chance_of_snow,
    this.condition,
    this.uv,
  });
  WatherModelForecastForecastdayDay.fromJson(Map<String, dynamic> json) {
    maxtemp_c = json['maxtemp_c']?.toDouble();
    maxtemp_f = json['maxtemp_f']?.toInt();
    mintemp_c = json['mintemp_c']?.toDouble();
    mintemp_f = json['mintemp_f']?.toDouble();
    avgtemp_c = json['avgtemp_c']?.toDouble();
    avgtemp_f = json['avgtemp_f']?.toDouble();
    maxwind_mph = json['maxwind_mph']?.toDouble();
    maxwind_kph = json['maxwind_kph']?.toDouble();
    totalprecip_mm = json['totalprecip_mm']?.toDouble();
    totalprecip_in = json['totalprecip_in']?.toDouble();
    totalsnow_cm = json['totalsnow_cm']?.toInt();
    avgvis_km = json['avgvis_km']?.toDouble();
    avgvis_miles = json['avgvis_miles']?.toInt();
    avghumidity = json['avghumidity']?.toInt();
    daily_will_it_rain = json['daily_will_it_rain']?.toInt();
    daily_chance_of_rain = json['daily_chance_of_rain']?.toInt();
    daily_will_it_snow = json['daily_will_it_snow']?.toInt();
    daily_chance_of_snow = json['daily_chance_of_snow']?.toInt();
    condition = (json['condition'] != null) ? WatherModelForecastForecastdayDayCondition.fromJson(json['condition']) : null;
    uv = json['uv']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['maxtemp_c'] = maxtemp_c;
    data['maxtemp_f'] = maxtemp_f;
    data['mintemp_c'] = mintemp_c;
    data['mintemp_f'] = mintemp_f;
    data['avgtemp_c'] = avgtemp_c;
    data['avgtemp_f'] = avgtemp_f;
    data['maxwind_mph'] = maxwind_mph;
    data['maxwind_kph'] = maxwind_kph;
    data['totalprecip_mm'] = totalprecip_mm;
    data['totalprecip_in'] = totalprecip_in;
    data['totalsnow_cm'] = totalsnow_cm;
    data['avgvis_km'] = avgvis_km;
    data['avgvis_miles'] = avgvis_miles;
    data['avghumidity'] = avghumidity;
    data['daily_will_it_rain'] = daily_will_it_rain;
    data['daily_chance_of_rain'] = daily_chance_of_rain;
    data['daily_will_it_snow'] = daily_will_it_snow;
    data['daily_chance_of_snow'] = daily_chance_of_snow;
    if (condition != null) {
      data['condition'] = condition!.toJson();
    }
    data['uv'] = uv;
    return data;
  }
}

class WatherModelForecastForecastday {
/*
{
  "date": "2023-08-22",
  "date_epoch": 1692662400,
  "day": {
    "maxtemp_c": 26.1,
    "maxtemp_f": 79,
    "mintemp_c": 21.3,
    "mintemp_f": 70.3,
    "avgtemp_c": 23.4,
    "avgtemp_f": 74.2,
    "maxwind_mph": 13.4,
    "maxwind_kph": 21.6,
    "totalprecip_mm": 12.9,
    "totalprecip_in": 0.51,
    "totalsnow_cm": 0,
    "avgvis_km": 7.6,
    "avgvis_miles": 4,
    "avghumidity": 88,
    "daily_will_it_rain": 1,
    "daily_chance_of_rain": 96,
    "daily_will_it_snow": 0,
    "daily_chance_of_snow": 0,
    "condition": {
      "text": "Moderate rain",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
      "code": 1189
    },
    "uv": 5
  },
  "astro": {
    "sunrise": "06:18 AM",
    "sunset": "07:01 PM",
    "moonrise": "10:59 AM",
    "moonset": "10:34 PM",
    "moon_phase": "Waxing Crescent",
    "moon_illumination": "26",
    "is_moon_up": 0,
    "is_sun_up": 0
  },
  "hour": [
    {
      "time_epoch": 1692642600,
      "time": "2023-08-22 00:00",
      "temp_c": 21.6,
      "temp_f": 70.9,
      "is_day": 0,
      "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
        "code": 1003
      },
      "wind_mph": 4,
      "wind_kph": 6.5,
      "wind_degree": 191,
      "wind_dir": "SSW",
      "pressure_mb": 1008,
      "pressure_in": 29.77,
      "precip_mm": 0,
      "precip_in": 0,
      "humidity": 94,
      "cloud": 38,
      "feelslike_c": 21.6,
      "feelslike_f": 70.9,
      "windchill_c": 21.6,
      "windchill_f": 70.9,
      "heatindex_c": 24.4,
      "heatindex_f": 75.9,
      "dewpoint_c": 20.6,
      "dewpoint_f": 69.1,
      "will_it_rain": 0,
      "chance_of_rain": 0,
      "will_it_snow": 0,
      "chance_of_snow": 0,
      "vis_km": 10,
      "vis_miles": 6,
      "gust_mph": 7.8,
      "gust_kph": 12.6,
      "uv": 1
    }
  ]
} 
*/

  String? date;
  int? date_epoch;
  WatherModelForecastForecastdayDay? day;
  WatherModelForecastForecastdayAstro? astro;
  List<WatherModelForecastForecastdayHour?>? hour;

  WatherModelForecastForecastday({
    this.date,
    this.date_epoch,
    this.day,
    this.astro,
    this.hour,
  });
  WatherModelForecastForecastday.fromJson(Map<String, dynamic> json) {
    date = json['date']?.toString();
    date_epoch = json['date_epoch']?.toInt();
    day = (json['day'] != null) ? WatherModelForecastForecastdayDay.fromJson(json['day']) : null;
    astro = (json['astro'] != null) ? WatherModelForecastForecastdayAstro.fromJson(json['astro']) : null;
  if (json['hour'] != null) {
  final v = json['hour'];
  final arr0 = <WatherModelForecastForecastdayHour>[];
  v.forEach((v) {
  arr0.add(WatherModelForecastForecastdayHour.fromJson(v));
  });
    hour = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['date_epoch'] = date_epoch;
    if (day != null) {
      data['day'] = day!.toJson();
    }
    if (astro != null) {
      data['astro'] = astro!.toJson();
    }
    if (hour != null) {
      final v = hour;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['hour'] = arr0;
    }
    return data;
  }
}

class WatherModelForecast {
/*
{
  "forecastday": [
    {
      "date": "2023-08-22",
      "date_epoch": 1692662400,
      "day": {
        "maxtemp_c": 26.1,
        "maxtemp_f": 79,
        "mintemp_c": 21.3,
        "mintemp_f": 70.3,
        "avgtemp_c": 23.4,
        "avgtemp_f": 74.2,
        "maxwind_mph": 13.4,
        "maxwind_kph": 21.6,
        "totalprecip_mm": 12.9,
        "totalprecip_in": 0.51,
        "totalsnow_cm": 0,
        "avgvis_km": 7.6,
        "avgvis_miles": 4,
        "avghumidity": 88,
        "daily_will_it_rain": 1,
        "daily_chance_of_rain": 96,
        "daily_will_it_snow": 0,
        "daily_chance_of_snow": 0,
        "condition": {
          "text": "Moderate rain",
          "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
          "code": 1189
        },
        "uv": 5
      },
      "astro": {
        "sunrise": "06:18 AM",
        "sunset": "07:01 PM",
        "moonrise": "10:59 AM",
        "moonset": "10:34 PM",
        "moon_phase": "Waxing Crescent",
        "moon_illumination": "26",
        "is_moon_up": 0,
        "is_sun_up": 0
      },
      "hour": [
        {
          "time_epoch": 1692642600,
          "time": "2023-08-22 00:00",
          "temp_c": 21.6,
          "temp_f": 70.9,
          "is_day": 0,
          "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
          },
          "wind_mph": 4,
          "wind_kph": 6.5,
          "wind_degree": 191,
          "wind_dir": "SSW",
          "pressure_mb": 1008,
          "pressure_in": 29.77,
          "precip_mm": 0,
          "precip_in": 0,
          "humidity": 94,
          "cloud": 38,
          "feelslike_c": 21.6,
          "feelslike_f": 70.9,
          "windchill_c": 21.6,
          "windchill_f": 70.9,
          "heatindex_c": 24.4,
          "heatindex_f": 75.9,
          "dewpoint_c": 20.6,
          "dewpoint_f": 69.1,
          "will_it_rain": 0,
          "chance_of_rain": 0,
          "will_it_snow": 0,
          "chance_of_snow": 0,
          "vis_km": 10,
          "vis_miles": 6,
          "gust_mph": 7.8,
          "gust_kph": 12.6,
          "uv": 1
        }
      ]
    }
  ]
} 
*/

  List<WatherModelForecastForecastday?>? forecastday;

  WatherModelForecast({
    this.forecastday,
  });
  WatherModelForecast.fromJson(Map<String, dynamic> json) {
  if (json['forecastday'] != null) {
  final v = json['forecastday'];
  final arr0 = <WatherModelForecastForecastday>[];
  v.forEach((v) {
  arr0.add(WatherModelForecastForecastday.fromJson(v));
  });
    forecastday = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (forecastday != null) {
      final v = forecastday;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['forecastday'] = arr0;
    }
    return data;
  }
}

class WatherModelCurrentCondition {
/*
{
  "text": "Light rain shower",
  "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
  "code": 1240
} 
*/

  String? text;
  String? icon;
  int? code;

  WatherModelCurrentCondition({
    this.text,
    this.icon,
    this.code,
  });
  WatherModelCurrentCondition.fromJson(Map<String, dynamic> json) {
    text = json['text']?.toString();
    icon = json['icon']?.toString();
    code = json['code']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['text'] = text;
    data['icon'] = icon;
    data['code'] = code;
    return data;
  }
}

class WatherModelCurrent {
/*
{
  "last_updated_epoch": 1692692100,
  "last_updated": "2023-08-22 13:45",
  "temp_c": 26.1,
  "temp_f": 79,
  "is_day": 1,
  "condition": {
    "text": "Light rain shower",
    "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
    "code": 1240
  },
  "wind_mph": 11.9,
  "wind_kph": 19.1,
  "wind_degree": 258,
  "wind_dir": "WSW",
  "pressure_mb": 1007,
  "pressure_in": 29.75,
  "precip_mm": 0.9,
  "precip_in": 0.04,
  "humidity": 78,
  "cloud": 83,
  "feelslike_c": 28.4,
  "feelslike_f": 83.1,
  "vis_km": 10,
  "vis_miles": 6,
  "uv": 6,
  "gust_mph": 17.2,
  "gust_kph": 27.7
} 
*/

  int? last_updated_epoch;
  String? last_updated;
  double? temp_c;
  int? temp_f;
  int? is_day;
  WatherModelCurrentCondition? condition;
  double? wind_mph;
  double? wind_kph;
  int? wind_degree;
  String? wind_dir;
  int? pressure_mb;
  double? pressure_in;
  double? precip_mm;
  double? precip_in;
  int? humidity;
  int? cloud;
  double? feelslike_c;
  double? feelslike_f;
  int? vis_km;
  int? vis_miles;
  int? uv;
  double? gust_mph;
  double? gust_kph;

  WatherModelCurrent({
    this.last_updated_epoch,
    this.last_updated,
    this.temp_c,
    this.temp_f,
    this.is_day,
    this.condition,
    this.wind_mph,
    this.wind_kph,
    this.wind_degree,
    this.wind_dir,
    this.pressure_mb,
    this.pressure_in,
    this.precip_mm,
    this.precip_in,
    this.humidity,
    this.cloud,
    this.feelslike_c,
    this.feelslike_f,
    this.vis_km,
    this.vis_miles,
    this.uv,
    this.gust_mph,
    this.gust_kph,
  });
  WatherModelCurrent.fromJson(Map<String, dynamic> json) {
    last_updated_epoch = json['last_updated_epoch']?.toInt();
    last_updated = json['last_updated']?.toString();
    temp_c = json['temp_c']?.toDouble();
    temp_f = json['temp_f']?.toInt();
    is_day = json['is_day']?.toInt();
    condition = (json['condition'] != null) ? WatherModelCurrentCondition.fromJson(json['condition']) : null;
    wind_mph = json['wind_mph']?.toDouble();
    wind_kph = json['wind_kph']?.toDouble();
    wind_degree = json['wind_degree']?.toInt();
    wind_dir = json['wind_dir']?.toString();
    pressure_mb = json['pressure_mb']?.toInt();
    pressure_in = json['pressure_in']?.toDouble();
    precip_mm = json['precip_mm']?.toDouble();
    precip_in = json['precip_in']?.toDouble();
    humidity = json['humidity']?.toInt();
    cloud = json['cloud']?.toInt();
    feelslike_c = json['feelslike_c']?.toDouble();
    feelslike_f = json['feelslike_f']?.toDouble();
    vis_km = json['vis_km']?.toInt();
    vis_miles = json['vis_miles']?.toInt();
    uv = json['uv']?.toInt();
    gust_mph = json['gust_mph']?.toDouble();
    gust_kph = json['gust_kph']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['last_updated_epoch'] = last_updated_epoch;
    data['last_updated'] = last_updated;
    data['temp_c'] = temp_c;
    data['temp_f'] = temp_f;
    data['is_day'] = is_day;
    if (condition != null) {
      data['condition'] = condition!.toJson();
    }
    data['wind_mph'] = wind_mph;
    data['wind_kph'] = wind_kph;
    data['wind_degree'] = wind_degree;
    data['wind_dir'] = wind_dir;
    data['pressure_mb'] = pressure_mb;
    data['pressure_in'] = pressure_in;
    data['precip_mm'] = precip_mm;
    data['precip_in'] = precip_in;
    data['humidity'] = humidity;
    data['cloud'] = cloud;
    data['feelslike_c'] = feelslike_c;
    data['feelslike_f'] = feelslike_f;
    data['vis_km'] = vis_km;
    data['vis_miles'] = vis_miles;
    data['uv'] = uv;
    data['gust_mph'] = gust_mph;
    data['gust_kph'] = gust_kph;
    return data;
  }
}

class WatherModelLocation {
/*
{
  "name": "Nasik",
  "region": "Maharashtra",
  "country": "India",
  "lat": 19.98,
  "lon": 73.8,
  "tz_id": "Asia/Kolkata",
  "localtime_epoch": 1692692516,
  "localtime": "2023-08-22 13:51"
} 
*/

  String? name;
  String? region;
  String? country;
  double? lat;
  double? lon;
  String? tz_id;
  int? localtime_epoch;
  String? localtime;

  WatherModelLocation({
    this.name,
    this.region,
    this.country,
    this.lat,
    this.lon,
    this.tz_id,
    this.localtime_epoch,
    this.localtime,
  });
  WatherModelLocation.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    region = json['region']?.toString();
    country = json['country']?.toString();
    lat = json['lat']?.toDouble();
    lon = json['lon']?.toDouble();
    tz_id = json['tz_id']?.toString();
    localtime_epoch = json['localtime_epoch']?.toInt();
    localtime = json['localtime']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['region'] = region;
    data['country'] = country;
    data['lat'] = lat;
    data['lon'] = lon;
    data['tz_id'] = tz_id;
    data['localtime_epoch'] = localtime_epoch;
    data['localtime'] = localtime;
    return data;
  }
}

class WatherModel {
/*
{
  "location": {
    "name": "Nasik",
    "region": "Maharashtra",
    "country": "India",
    "lat": 19.98,
    "lon": 73.8,
    "tz_id": "Asia/Kolkata",
    "localtime_epoch": 1692692516,
    "localtime": "2023-08-22 13:51"
  },
  "current": {
    "last_updated_epoch": 1692692100,
    "last_updated": "2023-08-22 13:45",
    "temp_c": 26.1,
    "temp_f": 79,
    "is_day": 1,
    "condition": {
      "text": "Light rain shower",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
      "code": 1240
    },
    "wind_mph": 11.9,
    "wind_kph": 19.1,
    "wind_degree": 258,
    "wind_dir": "WSW",
    "pressure_mb": 1007,
    "pressure_in": 29.75,
    "precip_mm": 0.9,
    "precip_in": 0.04,
    "humidity": 78,
    "cloud": 83,
    "feelslike_c": 28.4,
    "feelslike_f": 83.1,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 6,
    "gust_mph": 17.2,
    "gust_kph": 27.7
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2023-08-22",
        "date_epoch": 1692662400,
        "day": {
          "maxtemp_c": 26.1,
          "maxtemp_f": 79,
          "mintemp_c": 21.3,
          "mintemp_f": 70.3,
          "avgtemp_c": 23.4,
          "avgtemp_f": 74.2,
          "maxwind_mph": 13.4,
          "maxwind_kph": 21.6,
          "totalprecip_mm": 12.9,
          "totalprecip_in": 0.51,
          "totalsnow_cm": 0,
          "avgvis_km": 7.6,
          "avgvis_miles": 4,
          "avghumidity": 88,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 96,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Moderate rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
            "code": 1189
          },
          "uv": 5
        },
        "astro": {
          "sunrise": "06:18 AM",
          "sunset": "07:01 PM",
          "moonrise": "10:59 AM",
          "moonset": "10:34 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": "26",
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1692642600,
            "time": "2023-08-22 00:00",
            "temp_c": 21.6,
            "temp_f": 70.9,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 191,
            "wind_dir": "SSW",
            "pressure_mb": 1008,
            "pressure_in": 29.77,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 94,
            "cloud": 38,
            "feelslike_c": 21.6,
            "feelslike_f": 70.9,
            "windchill_c": 21.6,
            "windchill_f": 70.9,
            "heatindex_c": 24.4,
            "heatindex_f": 75.9,
            "dewpoint_c": 20.6,
            "dewpoint_f": 69.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 1
          }
        ]
      }
    ]
  }
} 
*/

  WatherModelLocation? location;
  WatherModelCurrent? current;
  WatherModelForecast? forecast;

  WatherModel({
    this.location,
    this.current,
    this.forecast,
  });
  WatherModel.fromJson(Map<String, dynamic> json) {
    location = (json['location'] != null) ? WatherModelLocation.fromJson(json['location']) : null;
    current = (json['current'] != null) ? WatherModelCurrent.fromJson(json['current']) : null;
    forecast = (json['forecast'] != null) ? WatherModelForecast.fromJson(json['forecast']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (location != null) {
      data['location'] = location!.toJson();
    }
    if (current != null) {
      data['current'] = current!.toJson();
    }
    if (forecast != null) {
      data['forecast'] = forecast!.toJson();
    }
    return data;
  }
}
