///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class CartModelDATA2 {
/*
{
  "TABLE2": 1
} 
*/

  String? TABLE2;

  CartModelDATA2({
    this.TABLE2,
  });
  CartModelDATA2.fromJson(Map<String, dynamic> json) {
    TABLE2 = json['TABLE2']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['TABLE2'] = TABLE2;
    return data;
  }
}

class CartModelDATA1 {
/*
{
  "TABLE1": 1
} 
*/

  String? TABLE1;

  CartModelDATA1({
    this.TABLE1,
  });
  CartModelDATA1.fromJson(Map<String, dynamic> json) {
    TABLE1 = json['TABLE1']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['TABLE1'] = TABLE1;
    return data;
  }
}

class CartModelDATA {
/*
{
  "CART_ID": 22439,
  "USER_ID": 21013,
  "PRODUCT_ID": 51,
  "PS_ID": 19,
  "QTY": 1,
  "PRODUCT_NAME": "डॉ.रिच",
  "PRODUCT_IMAGE": "https://myadmin.cropguru.in//Images/Product71887166838314512023.png",
  "DESCRIPTION": "",
  "SIZE": 500,
  "CASE_SIZE": 1,
  "PRICE": 655,
  "DISCOUNT": 98,
  "DISCOUNT_IN_PERCENTAGE": 14.961832061068703,
  "UNIT_ID": 2,
  "SIZE_IMAGES": "https://myadmin.cropguru.in//Images/Product71887166838314512023.png",
  "UNIT": "ml"
} 
*/

  String? CART_ID;
  String? USER_ID;
  String? PRODUCT_ID;
  String? PS_ID;
  String? QTY;
  String? PRODUCT_NAME;
  String? PRODUCT_IMAGE;
  String? DESCRIPTION;
  String? SIZE;
  String? CASE_SIZE;
  int? PRICE;
  int? DISCOUNT;
  int? DISCOUNT_IN_PERCENTAGE;
  String? UNIT_ID;
  String? SIZE_IMAGES;
  String? UNIT;

  CartModelDATA({
    this.CART_ID,
    this.USER_ID,
    this.PRODUCT_ID,
    this.PS_ID,
    this.QTY,
    this.PRODUCT_NAME,
    this.PRODUCT_IMAGE,
    this.DESCRIPTION,
    this.SIZE,
    this.CASE_SIZE,
    this.PRICE,
    this.DISCOUNT,
    this.DISCOUNT_IN_PERCENTAGE,
    this.UNIT_ID,
    this.SIZE_IMAGES,
    this.UNIT,
  });
  CartModelDATA.fromJson(Map<String, dynamic> json) {
    CART_ID = json['CART_ID']?.toString();
    USER_ID = json['USER_ID']?.toString();
    PRODUCT_ID = json['PRODUCT_ID']?.toString();
    PS_ID = json['PS_ID']?.toString();
    QTY = json['QTY']?.toString();
    PRODUCT_NAME = json['PRODUCT_NAME']?.toString();
    PRODUCT_IMAGE = json['PRODUCT_IMAGE']?.toString();
    DESCRIPTION = json['DESCRIPTION']?.toString();
    SIZE = json['SIZE']?.toString();
    CASE_SIZE = json['CASE_SIZE']?.toString();
    PRICE = (json['PRICE']as num?)?.toInt() ?? 0;
    DISCOUNT = (json['DISCOUNT']as num?)?.toInt() ?? 0;
    DISCOUNT_IN_PERCENTAGE = (json['DISCOUNT_IN_PERCENTAGE']as num?)?.toInt() ?? 0;
    UNIT_ID = json['UNIT_ID']?.toString();
    SIZE_IMAGES = json['SIZE_IMAGES']?.toString();
    UNIT = json['UNIT']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['CART_ID'] = CART_ID;
    data['USER_ID'] = USER_ID;
    data['PRODUCT_ID'] = PRODUCT_ID;
    data['PS_ID'] = PS_ID;
    data['QTY'] = QTY;
    data['PRODUCT_NAME'] = PRODUCT_NAME;
    data['PRODUCT_IMAGE'] = PRODUCT_IMAGE;
    data['DESCRIPTION'] = DESCRIPTION;
    data['SIZE'] = SIZE;
    data['CASE_SIZE'] = CASE_SIZE;
    data['PRICE'] = PRICE;
    data['DISCOUNT'] = DISCOUNT;
    data['DISCOUNT_IN_PERCENTAGE'] = DISCOUNT_IN_PERCENTAGE;
    data['UNIT_ID'] = UNIT_ID;
    data['SIZE_IMAGES'] = SIZE_IMAGES;
    data['UNIT'] = UNIT;
    return data;
  }
}

class CartModel {
/*
{
  "ResponseCode": "0",
  "ResponseMessage": "Get_MyCartList List",
  "ID": null,
  "DATA": [
    {
      "CART_ID": 22439,
      "USER_ID": 21013,
      "PRODUCT_ID": 51,
      "PS_ID": 19,
      "QTY": 1,
      "PRODUCT_NAME": "डॉ.रिच",
      "PRODUCT_IMAGE": "https://myadmin.cropguru.in//Images/Product71887166838314512023.png",
      "DESCRIPTION": "",
      "SIZE": 500,
      "CASE_SIZE": 1,
      "PRICE": 655,
      "DISCOUNT": 98,
      "DISCOUNT_IN_PERCENTAGE": 14.961832061068703,
      "UNIT_ID": 2,
      "SIZE_IMAGES": "https://myadmin.cropguru.in//Images/Product71887166838314512023.png",
      "UNIT": "ml"
    }
  ],
  "DATA1": [
    {
      "TABLE1": 1
    }
  ],
  "DATA2": [
    {
      "TABLE2": 1
    }
  ]
} 
*/

  String? ResponseCode;
  String? ResponseMessage;
  String? ID;
  List<CartModelDATA?>? DATA;
  List<CartModelDATA1?>? DATA1;
  List<CartModelDATA2?>? DATA2;

  CartModel({
    this.ResponseCode,
    this.ResponseMessage,
    this.ID,
    this.DATA,
    this.DATA1,
    this.DATA2,
  });
  CartModel.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseMessage = json['ResponseMessage']?.toString();
    ID = json['ID']?.toString();
  if (json['DATA'] != null) {
  final v = json['DATA'];
  final arr0 = <CartModelDATA>[];
  v.forEach((v) {
  arr0.add(CartModelDATA.fromJson(v));
  });
    DATA = arr0;
    }
  if (json['DATA1'] != null) {
  final v = json['DATA1'];
  final arr0 = <CartModelDATA1>[];
  v.forEach((v) {
  arr0.add(CartModelDATA1.fromJson(v));
  });
    DATA1 = arr0;
    }
  if (json['DATA2'] != null) {
  final v = json['DATA2'];
  final arr0 = <CartModelDATA2>[];
  v.forEach((v) {
  arr0.add(CartModelDATA2.fromJson(v));
  });
    DATA2 = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseMessage'] = ResponseMessage;
    data['ID'] = ID;
    if (DATA != null) {
      final v = DATA;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA'] = arr0;
    }
    if (DATA1 != null) {
      final v = DATA1;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA1'] = arr0;
    }
    if (DATA2 != null) {
      final v = DATA2;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA2'] = arr0;
    }
    return data;
  }
}
