///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class ShopByCateModelDATA2 {
/*
{
  "Column1": 1
} 
*/

  String? Column1;

  ShopByCateModelDATA2({
    this.Column1,
  });
  ShopByCateModelDATA2.fromJson(Map<String, dynamic> json) {
    Column1 = json['Column1']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Column1'] = Column1;
    return data;
  }
}

class ShopByCateModelDATA {
/*
{
  "PCAT_ID": 1,
  "PCAT_NAME": "Crop protectors",
  "PCAT_IMAGE": "https://myadmin.cropguru.in//Images/Category75786988718527292023.jpg"
} 
*/

  String? PCAT_ID;
  String? PCAT_NAME;
  String? PCAT_IMAGE;

  ShopByCateModelDATA({
    this.PCAT_ID,
    this.PCAT_NAME,
    this.PCAT_IMAGE,
  });
  ShopByCateModelDATA.fromJson(Map<String, dynamic> json) {
    PCAT_ID = json['PCAT_ID']?.toString();
    PCAT_NAME = json['PCAT_NAME']?.toString();
    PCAT_IMAGE = json['PCAT_IMAGE']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['PCAT_ID'] = PCAT_ID;
    data['PCAT_NAME'] = PCAT_NAME;
    data['PCAT_IMAGE'] = PCAT_IMAGE;
    return data;
  }
}

class ShopByCateModel {
/*
{
  "ResponseCode": "0",
  "ResponseMessage": "List Of Category",
  "ID": null,
  "DATA": [
    {
      "PCAT_ID": 1,
      "PCAT_NAME": "Crop protectors",
      "PCAT_IMAGE": "https://myadmin.cropguru.in//Images/Category75786988718527292023.jpg"
    }
  ],
  "DATA1": [
    null
  ],
  "DATA2": [
    {
      "Column1": 1
    }
  ]
} 
*/

  String? ResponseCode;
  String? ResponseMessage;
  String? ID;
  List<ShopByCateModelDATA?>? DATA;
  List<String?>? DATA1;
  List<ShopByCateModelDATA2?>? DATA2;

  ShopByCateModel({
    this.ResponseCode,
    this.ResponseMessage,
    this.ID,
    this.DATA,
    this.DATA1,
    this.DATA2,
  });
  ShopByCateModel.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseMessage = json['ResponseMessage']?.toString();
    ID = json['ID']?.toString();
  if (json['DATA'] != null) {
  final v = json['DATA'];
  final arr0 = <ShopByCateModelDATA>[];
  v.forEach((v) {
  arr0.add(ShopByCateModelDATA.fromJson(v));
  });
    DATA = arr0;
    }
   
  if (json['DATA2'] != null) {
  final v = json['DATA2'];
  final arr0 = <ShopByCateModelDATA2>[];
  v.forEach((v) {
  arr0.add(ShopByCateModelDATA2.fromJson(v));
  });
    DATA2 = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseMessage'] = ResponseMessage;
    data['ID'] = ID;
    if (DATA != null) {
      final v = DATA;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA'] = arr0;
    }
    
    if (DATA2 != null) {
      final v = DATA2;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA2'] = arr0;
    }
    return data;
  }
}
